repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: debug-statements
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-ast
      - id: fix-byte-order-marker
      - id: check-json
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-toml
      - id: check-yaml
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: no-commit-to-branch
        args: [-b, main]
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: check-datetime-now
        name: check_datetime_now
        description: Prefer datetime.utcnow()
        language: pygrep
        entry: 'datetime\.now\(\)'
        types: [python]

  - repo: https://github.com/twu/skjold
    rev: v0.5.1
    hooks:
      - id: skjold

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        exclude: poetry.lock

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ["--exclude=docs/*,*migrations*", "--ignore=E501,W503,E203"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-mock-methods

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        additional_dependencies: ["toml"]
        args: [--add-ignore=D1, -e]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.10.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "3.2"]

  - repo: https://github.com/olist/hulks.git
    rev: 0.4.1
    hooks:
      - id: check-filename
      - id: check-invalid-domains
      - id: check-logger
      - id: check-default-commentary-django-migration
      - id: check-django-migrations-filename
      - id: check-mutable-defaults
