# Generated by Django 4.1.5 on 2023-01-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentDbt",
            fields=[
                ("debtId", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("government_id", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("debt_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("debt_due_date", models.DateField()),
            ],
        ),
    ]
