# Generated by Django 4.1.5 on 2023-01-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentDebt",
            fields=[
                ("debt_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("government_id", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("debt_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("debt_due_date", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="PaymentDbt",
        ),
    ]
