# Generated by Django 4.1.5 on 2023-01-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments_api", "0002_paymentdebt_delete_paymentdbt"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdebt",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("payed", "Payed")],
                default="open",
                max_length=32,
            ),
        ),
    ]
