# Generated by Django 4.1.5 on 2023-01-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments_api", "0003_paymentdebt_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentdebt",
            name="government_id",
            field=models.BigIntegerField(),
        ),
    ]
